import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import { canonicalizeObservations } from "./canonicalize";
import { adaptGitHubActivities } from "./github-adapter";
import { adaptLocalRunBundle, loadLocalRunBundle } from "./local-run-adapter";
import { deriveExperimentalWorkshopState } from "./projection";
import { localRunBundleSchema, workObservationSchema } from "./schema";
import type { WorkObservation } from "./types";

const asOf = "2026-09-19T18:00:00.000Z";
const digest = (value: string) => createHash("sha256").update(value).digest("hex");
const observation = (overrides: Record<string, unknown> = {}): WorkObservation => ({
  schemaVersion: "work-observation-v1", id: "local-run:event-1", kind: "artifact_changed", actor: { id: "agent-run:run-1", label: "Agent" }, reporter: { id: "collector:local" }, run: { id: "local-run:run-1" }, repository: { id: "github-repository:1373439999", name: "jayjz/TEMPER" }, occurredAt: "2026-09-19T10:00:00.000Z", observedAt: "2026-09-19T10:01:00.000Z", provenance: { source: "local-run", sourceFactId: "local-run-fact:event-1", collector: "collector:local" }, evidence: [{ reference: "patch", path: "patch.diff", sha256: "a".repeat(64) }], body: { before: { revision: "before" }, after: { revision: "after" }, patchEvidence: "patch" }, ...overrides,
} as WorkObservation);

const bundle = (facts: unknown[]) => ({ schemaVersion: "buildblock-local-run-v1", sourceInstance: "collector:local", repository: { id: "github-repository:1373439999", name: "jayjz/TEMPER" }, run: { id: "local-run:run-1" }, actor: { id: "agent-run:run-1" }, reporter: { id: "collector:local" }, facts });
const evidence = (path: string, content: string) => ({ reference: path, path, sha256: digest(content) });
const factBase = (id: string, kind: string, file: string, content: string) => ({ id, kind, occurredAt: "2026-09-19T10:00:00.000Z", observedAt: "2026-09-19T10:01:00.000Z", evidence: [evidence(file, content)] });
function writeBundle(root: string, facts: unknown[], files: Record<string, string>) { mkdirSync(root, { recursive: true }); for (const [name, content] of Object.entries(files)) writeFileSync(join(root, name), content); writeFileSync(join(root, "manifest.json"), JSON.stringify(bundle(facts))); }
const association = { repositoryId: "github-repository:1373439999", workshopId: "jayjz-workshop" };

describe("work-observation-v1", () => {
  it("runtime-validates the contract and keeps actor distinct from reporter", () => { expect(workObservationSchema.parse(observation()).actor.id).not.toBe(workObservationSchema.parse(observation()).reporter.id); expect(workObservationSchema.safeParse({ ...observation(), schemaVersion: "wrong" }).success).toBe(false); });
  it("collapses duplicates, is order-independent, and quarantines conflicts", () => { const first = observation(); const duplicate = structuredClone(first); const second = observation({ id: "local-run:event-2", occurredAt: "2026-09-19T11:00:00.000Z" }); expect(canonicalizeObservations([first, duplicate, second]).observations).toEqual(canonicalizeObservations([second, first, duplicate]).observations); const conflict = observation({ body: { before: { revision: "before" }, after: { revision: "other" }, patchEvidence: "patch" } }); const result = canonicalizeObservations([first, conflict]); expect(result.observations).toEqual([]); expect(result.diagnostics[0]?.code).toBe("conflicting_immutable_event_id"); });
  it("keeps source namespaces distinct", () => { expect(canonicalizeObservations([observation({ id: "github:event-1" }), observation({ id: "local-run:event-1" })]).observations).toHaveLength(2); });
  it("does not admit agent claims as source observations", () => { expect(localRunBundleSchema.safeParse({ ...bundle([]), observations: [observation()] }).success).toBe(false); });
});

describe("local-run bundle loading", () => {
  it("requires concrete artifact evidence and binds verification to the captured revision", () => { const root = mkdtempSync(join(tmpdir(), "work-bundle-")); const patch = "diff --git a/a b/a\n"; const command = "1 passed\n"; const capture = { ...factBase("local-run-fact:capture", "worktree.captured", "patch.diff", patch), beforeRevision: "0747730", afterRevision: "content:after", patchEvidence: "patch.diff" }; const verification = { ...factBase("local-run-fact:command", "command.finished", "command.txt", command), executionId: "local-run-execution:1", checkKey: "pytest-metrics", revision: "content:after", startedAt: "2026-09-19T10:02:00.000Z", finishedAt: "2026-09-19T10:03:00.000Z", outcome: "passed", executionEvidence: "command.txt" }; writeBundle(root, [capture, verification], { "patch.diff": patch, "command.txt": command }); const loaded = loadLocalRunBundle(root); expect(loaded.diagnostics).toEqual([]); const derived = adaptLocalRunBundle(loaded.bundle!); expect(derived.observations.map((item) => item.kind)).toEqual(["artifact_changed", "verification_finished"]); });
  it("rejects unsupported manifests and artifact facts without patch evidence", () => { const patch = "patch"; const incomplete = { ...factBase("local-run-fact:incomplete", "worktree.captured", "patch.diff", patch), beforeRevision: "before", afterRevision: "after" }; expect(localRunBundleSchema.safeParse(bundle([incomplete])).success).toBe(false); expect(localRunBundleSchema.safeParse({ ...bundle([]), schemaVersion: "buildblock-local-run-v0" }).success).toBe(false); });
  it("rejects missing artifact evidence, bad digests, traversal, and escaping symlinks", () => { const root = mkdtempSync(join(tmpdir(), "work-bundle-invalid-")); const patch = "patch"; const capture = { ...factBase("local-run-fact:capture", "worktree.captured", "patch.diff", patch), beforeRevision: "before", afterRevision: "after", patchEvidence: "patch.diff" }; writeBundle(root, [capture], { "patch.diff": patch }); expect(loadLocalRunBundle(root).diagnostics).toEqual([]); writeFileSync(join(root, "patch.diff"), "changed"); expect(loadLocalRunBundle(root).diagnostics[0]?.code).toBe("bad_evidence_digest"); writeBundle(root, [{ ...capture, evidence: [evidence("../outside", patch)] }], { "patch.diff": patch }); expect(loadLocalRunBundle(root).diagnostics[0]?.code).toBe("unsafe_evidence_path"); writeBundle(root, [{ ...capture, evidence: [evidence("link.diff", patch)] }], {}); const outside = join(root, "..", "work-outside.diff"); writeFileSync(outside, patch); symlinkSync(outside, join(root, "link.diff")); expect(loadLocalRunBundle(root).diagnostics[0]?.code).toBe("escaping_symlink"); });
  it("retains unbound verification only as a diagnostic", () => { const command = "result"; const parsed = localRunBundleSchema.parse(bundle([{ ...factBase("local-run-fact:command", "command.finished", "command.txt", command), executionId: "local-run-execution:bad", checkKey: "check", revision: "not-captured", startedAt: "2026-09-19T10:02:00.000Z", finishedAt: "2026-09-19T10:03:00.000Z", outcome: "passed", executionEvidence: "command.txt" }])); expect(adaptLocalRunBundle(parsed).diagnostics[0]?.code).toBe("unbound_verification"); });
});

describe("experimental workshop projection", () => {
  it("excludes future occurrence and future observation, including stale reimport timing", () => { const past = observation(); const futureOccurred = observation({ id: "local-run:future-occurs", occurredAt: "2026-09-20T00:00:00.000Z" }); const futureObserved = observation({ id: "local-run:future-observed", observedAt: "2026-09-20T00:00:00.000Z" }); expect(deriveExperimentalWorkshopState([past, futureOccurred, futureObserved], association, asOf).repositories[0]?.supportingObservationIds).toEqual([past.id]); });
  it("keeps old source timestamps when the same bundle is reimported later", () => { const old = observation({ occurredAt: "2026-09-01T10:00:00.000Z", observedAt: "2026-09-01T10:01:00.000Z" }); expect(deriveExperimentalWorkshopState([old], association, asOf).repositories[0]?.supportingObservationIds).toEqual([old.id]); });
  it("keeps run-only and verification-only evidence detail-only", () => { const run = observation({ id: "local-run:run", kind: "run_started", body: { runId: "local-run:run-1" } }); const verification = observation({ id: "local-run:check", kind: "verification_finished", body: { executionId: "local-run-execution:1", checkKey: "check", revision: "after", startedAt: "2026-09-19T10:00:00.000Z", finishedAt: "2026-09-19T10:01:00.000Z", outcome: "passed", executionEvidence: "output" } }); expect(deriveExperimentalWorkshopState([run, verification], association, asOf).repositories).toEqual([]); });
  it("creates one observed repository and never multiplies markers", () => { const change = observation(); const repeated = observation({ id: "local-run:second" }); const state = deriveExperimentalWorkshopState([change, repeated], association, asOf); expect(state.repositories).toHaveLength(1); expect(state.repositories[0]).toMatchObject({ observed: true, integrationObserved: false, publicationObserved: false }); });
});

describe("GitHub adapter", () => {
  it("maps existing normalized semantics without changing their identity", () => { const result = adaptGitHubActivities([{ id: "push:1373439999:abc", kind: "code_pushed", developerId: 1, login: "jayjz", repository: { id: 1373439999, name: "jayjz/TEMPER" }, occurredAt: "2026-09-19T10:00:00.000Z", evidenceUrl: "https://github.com/jayjz/TEMPER/commit/abc", sourceEventIds: ["123"] }], asOf); expect(result.observations[0]).toMatchObject({ id: "github:push:1373439999:abc", kind: "artifact_changed", provenance: { sourceFactId: "github-event:123" } }); });
});
